source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'libPhoneNumber-iOS', '~> 0.7.5'
